spring.application.name=todo-jpa

server.port=9090
#Base URL:
server.servlet.context-path=/app

#JDBC (Java database connection) connection URL:

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_jpa
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Ai model from OpenAI:
openai.model=${OPENAI_MODEL:gpt-5.6-luna}

# Initial admin details:

app.admin.email=${ADMIN_EMAIL}
app.admin.firstName=${ADMIN_FIRST_NAME:admin}
app.admin.lastName=${ADMIN_LAST_NAME:admin}
app.admin.address=${ADMIN_ADDRESS:Geneva}
app.admin.password=${ADMIN_PASSWORD}